spring:
  datasource:
    #schema: classpath*:scripts/schema.sql
    #continue-on-error: false
    #sql-script-encoding: utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.356.25.190:3306/chai_mlog?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8&&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  flyway:
    enabled: true
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate.format_sql: true
      hibernate.naming.physical-strategy: org.hibernate.scripts.model.naming.PhysicalNamingStrategyStandardImpl
      hibernate.cache.use_second_level_cache: false
      hibernate.search.default.directory_provider: filesystem
      hibernate.search.default.indexBase: ${site.location}/storage/indexes